[package]
name = "teus"
version = "0.1.0"
edition = "2024"
authors = ['gdjohn4s']

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
chrono = "0.4.40"
ctrlc = "3.4.5"
rusqlite = "0.34.0"
serde = { version = "1.0.218", features = ["derive"] }
sysinfo = "0.33.1"
toml = "0.8.20"
